<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_DQProject_SQL_Optimasi_DQPizza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><span style='color:#0B2F9F'>Latar Belakang</span></b>

Di sebuah sudut kota Jakarta, telah didirikan sebuah restoran pizza bernama DQPizza.

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQLab%20-%20DQPizza%20Resto%20(1).png" width="30%">

Selama satu tahun terakhir, telah dilakukan pencatatan atas setiap transaksi yang terjadi. Mulai dari pemesanan menu hingga pembayaran pelanggan. Banyak data telah dikumpulkan dan dicatat. Namun, belum dilakukan pemanfaatan optimal terhadap informasi yang tersedia.

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Aksara.png" width="30%">

Pemilik restoran menginginkan agar data ini dapat dianalisis guna menemukan ruang untuk perbaikan dan melakukan efisiensi operasional sehingga diharapkan dapat meningkatkan penjualan pizza, menekan biaya operasional dan meningkatkan *customer experience*


# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [2]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated


In [3]:
# Inisialisasi project_id dan dataset_id
project_id = 'dqlabs-project'

# Buat BigQuery client
client = bigquery.Client(project = project_id)

# <b><span style='color:#0B2F9F'>Data Digunakan</span></b>

In [3]:
%%bigquery --project {project_id} --verbose

SELECT
  *
FROM dqpizza.tbl_detail_transaction

Executing query with job ID: 6fa59cef-d198-43bc-a892-ada77dead8b7
Query executing: 1.64s
Job ID 6fa59cef-d198-43bc-a892-ada77dead8b7 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,pizza_id,customer_id,order_maker_id,order_date,customer_name,customer_gender,customer_age,customer_tenure_in_months,...,pizza_size,pizza_price,pizza_production_cost,quantity,pizza_ingredients,order_time,completion_time,duration_in_minutes,is_complain,complain_detail
0,TRX016516,TRXD037417,PIZZA_BBQ_CKN_L,CUST002835,EMP000646,2025-10-06,Adinata Tamba,M,51,11,...,L,168075.0,133245.0,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",15:10:43,15:33:39,23,0,None
1,TRX001090,TRXD002450,PIZZA_BBQ_CKN_L,CUST002835,EMP000437,2025-01-19,Adinata Tamba,M,51,11,...,L,168075.0,133245.0,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",12:14:24,12:40:51,26,0,None
2,TRX005336,TRXD012151,PIZZA_BBQ_CKN_L,CUST002835,EMP000560,2025-03-31,Adinata Tamba,M,51,11,...,L,168075.0,133245.0,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",15:32:39,15:55:36,23,0,None
3,TRX018205,TRXD041351,PIZZA_BBQ_CKN_L,CUST002835,EMP000756,2025-11-06,Adinata Tamba,M,51,11,...,L,168075.0,133245.0,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",20:45:57,21:05:31,20,0,None
4,TRX000190,TRXD000447,PIZZA_BBQ_CKN_L,CUST002835,EMP000560,2025-01-03,Adinata Tamba,M,51,11,...,L,168075.0,133245.0,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",20:14:23,20:31:29,17,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX005110,TRXD011627,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000560,2025-03-27,Zulaikha Yuliarti,F,31,12,...,S,97200.0,69093.0,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",18:26:20,18:53:34,27,0,None
48615,TRX001363,TRXD003082,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000286,2025-01-23,Zulaikha Yuliarti,F,31,12,...,S,97200.0,69093.0,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",17:46:45,17:57:31,11,0,None
48616,TRX016225,TRXD036761,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000302,2025-09-30,Zulaikha Yuliarti,F,31,12,...,S,97200.0,69093.0,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",20:11:25,20:35:45,24,0,None
48617,TRX019679,TRXD044784,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000646,2025-12-01,Zulaikha Yuliarti,F,31,12,...,S,97200.0,69093.0,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",12:21:24,12:46:12,25,0,None


## **Area 1 - Performance Summary**

_Bagaimana tren jumlah transaksi dan total pendapatan penjualan pizza di DQPizza setiap bulan selama periode 2024? Adakah pola menarik yang kamu temukan?_

**Hint :**
* Tentukan periode waktu yang ingin dianalisis, yaitu setiap bulan dalam satu tahun.
* Kelompokkan data transaksi berdasarkan bulan terjadinya pembelian.
* Hitung jumlah transaksi yang terjadi di setiap bulan untuk melihat seberapa ramai penjualan pada periode tersebut.
* Hitung juga total pendapatan di setiap bulan untuk mengetahui seberapa besar nilai penjualan yang dihasilkan.
* Urutkan hasilnya dari bulan awal hingga akhir tahun agar terlihat jelas tren pergerakan penjualan dari waktu ke waktu.
* Analisis hasilnya untuk menemukan pola seperti bulan dengan penjualan tertinggi, periode sepi transaksi, atau potensi momen promosi.
* Expected Output :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Performance%20Summary.png" width="30%">



In [8]:
%%bigquery summary_trx_per_month --project {project_id} --verbose
SELECT
  FORMAT_DATE('%B', order_date) AS month_name,
  EXTRACT(MONTH FROM order_date) AS month_num,
  COUNT(DISTINCT order_id) AS total_trx,
  SUM(pizza_price) AS total_revenue
FROM
  dqpizza.tbl_detail_transaction
WHERE
  EXTRACT(YEAR FROM order_date) = 2025
GROUP BY
  month_name, month_num
ORDER BY
  month_num ASC

Executing query with job ID: 91e106b2-1c4b-4c3a-aa0c-03dc9abeb2b5
Query executing: 0.62s
Job ID 91e106b2-1c4b-4c3a-aa0c-03dc9abeb2b5 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [9]:
# Tampilkan hasilnya
display(summary_trx_per_month)

,month_name,month_num,total_trx,total_revenue
0,January,1,1845,554628870.0
1,February,2,1685,518945940.0
2,March,3,1840,560503800.0
3,April,4,1795,544493745.0
4,May,5,1853,566508735.0
5,June,6,1773,541050030.0
6,July,7,1935,575322345.0
7,August,8,1841,543257280.0
8,September,9,1661,510660450.0
9,October,10,1646,506788650.0


In [10]:
#@title ***DQPizza Performance Summary in 2025*** {display-mode: 'form'}

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(
    rows = 2,
    cols = 1,
    shared_xaxes = True,
    row_heights = [0.50, 0.75],
    vertical_spacing = 0.01
)

# Line chart pada subplot 1
fig.add_trace(
    px.line(
        summary_trx_per_month,
        x = 'month_name',
        y = 'total_trx',
        markers = True,
        color_discrete_sequence=['#03c03c'],
        labels = dict(
            x = 'month_name',
            y = 'total_trx'
        ),
        line_shape='linear'
    ).data[0],
    row = 1,
    col = 1
)

for i in [0, 11]:
    last_month_trx = summary_trx_per_month.loc[i, 'month_name']
    last_value_trx = summary_trx_per_month.loc[i, 'total_trx']
    if(i == 11):
        add_y = -100
    else:
        add_y = 100
    fig.add_annotation(
        x = last_month_trx,
        y = last_value_trx + add_y,
        text = f'<b>{last_month_trx}</b><br>Total Transaction : {last_value_trx}',
        showarrow = False,
        font = dict(
            color='#03c03c',
            family = "sans serif",
            size = 15,
        )
    )

fig.update_layout(
    yaxis = dict(
        showline = False,
        showgrid = False,
        showticklabels = False,
    )
)

# Add annotation for the maximum value with distance
max_month_trx = summary_trx_per_month.loc[summary_trx_per_month['total_trx'].idxmax(), 'month_name']
max_value_trx = summary_trx_per_month['total_trx'].max()

fig.add_annotation(
    x = max_month_trx,
    y = max_value_trx + 100,
    text = f'<b>{max_month_trx}</b><br>Best Transaction : {max_value_trx}',
    showarrow = False,
    font = dict(
        color='#02862a',
        family = "sans serif",
        size = 15,
    )
)

# Add line chart to the second row
fig.add_trace(
    px.bar(
        summary_trx_per_month,
        x = 'month_name',
        y = 'total_revenue',
        color_discrete_sequence=['#03c03c'],
        labels = dict(
            x = 'month_name',
            y = 'total_revenue'
          ),
          text = ['IDR ' + str(round(value / 1000000, 1)) + 'jt' for value in summary_trx_per_month['total_revenue']]
        ).data[0],
        row = 2,
        col = 1
    )

    # Update layout
fig.update_layout(
    height = 600,
    width = 1200,
    bargap = 0.05,
    showlegend = False,
    plot_bgcolor = 'rgba(0, 0, 0, 0)',
    paper_bgcolor = 'rgba(0, 0, 0, 0)',
    title = {
        'text': '<b>DQPizza Performance Summary in 2025</b>',
        'font': {'color': '#02862a', 'size': 20},
        'x' : 0.085
    }
)

"""
    fig.update_traces(
        marker = dict(
            color= ['#02862a' if val == 1 else '#03c03c' for val in summary_trx_per_month['rank_revenue']]
        )
    )
"""

fig.update_xaxes(showgrid=False)
fig.update_yaxes(
    showgrid  = False,
    visible = False,
    tickfont_color = "white"
)

fig.show()

**Kesimpulan :**     

...

## **Area 2 - Product**

**Total Order per Pizza Name**

_Jenis pizza apa saja yang paling banyak dipesan berdasarkan data transaksi DQPizza? Tampilkan top 10 pizza_

* Gunakan data transaksi penjualan pizza dari dataset DQPizza.
* Gabungkan informasi kategori dan nama pizza agar setiap jenis produk dapat dikenali dengan jelas.
* Hitung jumlah pesanan untuk setiap jenis pizza guna melihat tingkat popularitasnya.
* Urutkan hasilnya dari yang paling sering dipesan hingga paling jarang.
* Tampilkan hanya 10 jenis pizza teratas agar fokus pada menu favorit pelanggan.
* Gunakan hasil ini untuk menganalisis preferensi pelanggan dan menentukan strategi promosi atau pengelolaan stok menu.
* Expected Output :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Product.png" width="40%">

In [26]:
%%bigquery total_order_per_pizzaname --project {project_id} --verbose
SELECT
  FORMAT('PIZZA %s | %s', REPLACE(pizza_category, '_', ' '), REPLACE(pizza_name, '_', ' ')) AS pizza_name,
  COUNT(order_details_id) AS total_order
FROM
  dqpizza.tbl_detail_transaction
GROUP BY
  pizza_category, pizza_name
ORDER BY
  total_order DESC
LIMIT 10

Executing query with job ID: 46371a4c-2fa1-4449-b6cd-46eab0ab06f9
Query executing: 0.74s
Job ID 46371a4c-2fa1-4449-b6cd-46eab0ab06f9 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [27]:
# Tampilkan hasilnya
display(total_order_per_pizzaname)

,pizza_name,total_order
0,PIZZA CLASSIC | THE CLASSIC DELUXE PIZZA,2416
1,PIZZA CLASSIC | THE HAWAIIAN PIZZA,2372
2,PIZZA CHICKEN | THE BARBECUE CHICKEN PIZZA,2372
3,PIZZA CLASSIC | THE PEPPERONI PIZZA,2369
4,PIZZA CHICKEN | THE THAI CHICKEN PIZZA,2315
5,PIZZA CHICKEN | THE CALIFORNIA CHICKEN PIZZA,2302
6,PIZZA SUPREME | THE SPICY ITALIAN PIZZA,1887
7,PIZZA SUPREME | THE SICILIAN PIZZA,1887
8,PIZZA CHICKEN | THE SOUTHWEST CHICKEN PIZZA,1885
9,PIZZA VEGGIE | THE FOUR CHEESE PIZZA,1851


In [28]:
#@title ***Total Order per Pizza Name*** {display-mode: 'form'}

import plotly.express as px

total_order_per_pizzaname.sort_values(
    by = 'total_order',
    ascending = True,
    ignore_index = True,
    inplace = True
)

total_order_per_pizzaname['pizza_name'] = total_order_per_pizzaname['pizza_name'].str.title()
total_order_per_pizzaname['pizza_name'] = '<b>' + total_order_per_pizzaname['pizza_name'].str.replace(' |', '</b> |')
total_order_per_pizzaname['Color'] = total_order_per_pizzaname['total_order'].apply(
    lambda x: 'Top' if x == total_order_per_pizzaname['total_order'].max() else 'Other'
)

fig = px.bar(
    total_order_per_pizzaname,
    x = 'total_order',
    y = 'pizza_name',
    orientation = 'h',
    color = 'Color',
    color_discrete_map = {
        'Other': '#85ff7a',
        'Top': '#2db83d'
    },
    text_auto = True
)

fig.update_layout(
    width = 950,
    height = 450,
    xaxis_title = '',
    yaxis_title = '',
    showlegend = False,
    plot_bgcolor = 'rgba(0, 0, 0, 0)',
    title = dict(
        text = '<b><i>Best Seller</i> Pizza Berdasarkan Nama</b><br><sup><sup>Periode 2025</sup></sup>',
        font = dict(color = '#D19C4B')
    )
)

fig.update_xaxes(showticklabels = False)

fig.update_traces(
    textposition = 'inside',
    hovertemplate = '<b>Pizza %{label}</b><br>Total Order = %{value}'
)

fig.show()


**Kesimpulan :**

Berdasarkan analisis 'Total Order per Pizza Name', `Pizza Classic | The Classic Deluxe Pizza` adalah yang paling banyak dipesan dengan total **2416** pesanan. `Pizza Chicken | The Barbecue Chicken Pizza` dan `Pizza Classic | The Hawaiian Pizza` mengikuti dengan masing-masing **2372** pesanan. Ini menunjukkan preferensi pelanggan yang kuat terhadap pizza klasik dan berbasis ayam. `Pizza Veggie | The Four Cheese Pizza` adalah yang paling sedikit dipesan di antara 10 teratas, dengan 1851 pesanan.

## **Area 3 - Service**

**Rata - Rata Pizza Dibuat Tiap Jam Setiap Harinya**

_Pada jam berapa pembuatan pizza di DQPizza paling banyak dilakukan di setiap hari dalam seminggu berdasarkan data?_

* Gunakan data transaksi dari dataset DQPizza yang memuat waktu pemesanan dan jumlah pizza yang dibuat.
* Identifikasi hari dan jam dari setiap transaksi untuk mengetahui kapan aktivitas pembuatan pizza terjadi.
* Hitung total jumlah pizza yang dibuat pada setiap kombinasi hari dan jam.
* Hitung rata-rata jumlah pizza yang dibuat pada setiap jam di setiap hari untuk menemukan pola konsistensi aktivitas produksi.
* Urutkan hasilnya berdasarkan rata-rata jumlah tertinggi agar terlihat waktu dengan aktivitas produksi paling sibuk.
* Gunakan hasil analisis ini untuk mengoptimalkan penjadwalan karyawan dan perencanaan bahan baku di dapur.
* Expected Output :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Rata%20-%20Rata%20Pizza%20Dibuat%20Tiap%20Jam%20Setiap%20Harinya.png" width="30%">

In [33]:
%%bigquery num_qty_per_hour --project {project_id} --verbose
SELECT
  EXTRACT(DAYOFWEEK FROM order_date) AS day_order,
  FORMAT_DATE('%A', order_date) AS day_trx,
  EXTRACT(HOUR FROM order_time) AS hour_trx,
  ROUND(SUM(quantity) / COUNT(DISTINCT order_date), 2) AS avg_quantity
FROM
  dqpizza.tbl_detail_transaction
GROUP BY
  day_trx, day_order, hour_trx
ORDER BY
  day_order ASC, hour_trx ASC

Executing query with job ID: e9838003-8faf-4aad-b7bb-68badb548c91
Query executing: 0.45s
Job ID e9838003-8faf-4aad-b7bb-68badb548c91 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [34]:
# Tampilkan hasilnya
display(num_qty_per_hour)

,day_order,day_trx,hour_trx,avg_quantity
0,1,Sunday,10,3.00
1,1,Sunday,11,9.81
2,1,Sunday,12,23.46
3,1,Sunday,13,16.73
4,1,Sunday,14,9.79
...,...,...,...,...
90,7,Saturday,19,11.10
91,7,Saturday,20,8.10
92,7,Saturday,21,6.20
93,7,Saturday,22,3.76


In [35]:
#@title ***Rata - Rata Pizza Dibuat Tiap Jam Setiap Harinya*** {display-mode: 'form'}

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

avg_qty_per_hour = num_qty_per_hour.groupby(['hour_trx'], as_index = False).agg(avg_qty_per_hour = ('avg_quantity', 'mean'))

day_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
num_qty_per_hour['day_trx'] = pd.Categorical(num_qty_per_hour['day_trx'], categories=day_order, ordered=True)

num_qty_per_hour_pivot = num_qty_per_hour.pivot(
    index = 'day_trx',
    columns = 'hour_trx',
    values = 'avg_quantity'
).sort_values(by = 'day_trx', ascending = False, ignore_index = False)

fig = make_subplots(
    rows = 2,
    cols = 1,
    shared_xaxes = True,
    row_heights = [0.25, 0.75],
    vertical_spacing = 0.01
)

fig.add_trace(
    px.bar(
        avg_qty_per_hour,
        x = 'hour_trx',
        y = 'avg_qty_per_hour',
        labels = dict(
            x = 'month_trx',
            y = 'total_revenue'
        ),
        color = 'avg_qty_per_hour',
    ).data[0],
    row = 1,
    col = 1
)

fig.update_layout(
    yaxis = dict(
        showline = False,
        showgrid = False,
        showticklabels = False,
    )
)

fig.add_trace(
    px.imshow(
        num_qty_per_hour_pivot
    ).data[0],
    row = 2,
    col = 1
)

fig.update(
    layout_coloraxis_showscale = False
)

fig.update_xaxes(
    automargin = True
)

fig.update_layout(
    height = 600,
    width = 700,
    bargap = 0.05,
    coloraxis_colorscale = 'oranges',
    xaxis_tickangle = 0,
    plot_bgcolor = 'rgba(0, 0, 0, 0)',
    paper_bgcolor = 'rgba(0, 0, 0, 0)',
    title = dict(
        text = '<b>Rata - Rata Pizza Dibuat Tiap Jam Setiap Harinya</b><br><sup><sup>Periode 2024</sup></sup>',
        font = dict(
            color = '#B54B1F'
        )
    )
)

fig.show()

### **Kesimpulan :**

Berdasarkan analisis heatmap **Rata-Rata Pizza Dibuat Tiap Jam**, kita dapat mengidentifikasi beberapa pola operasional utama:

1.  **Puncak Produksi (Peak Hours):** Aktivitas pembuatan pizza paling tinggi terjadi secara konsisten pada pukul **12:00 - 13:00 (Makan Siang)** dan pukul **17:00 - 19:00 (Makan Malam)** hampir di setiap hari.
2.  **Hari Tersibuk:** Hari **Minggu (Sunday)** dan **Kamis (Thursday)** menunjukkan rata-rata produksi tertinggi pada jam makan siang (pukul 12:00), dengan angka mencapai lebih dari 22-23 pizza per jam.
3.  **Konsistensi Akhir Pekan:** Pada hari Jumat dan Sabtu, aktivitas produksi cenderung lebih bertahan lama hingga malam hari (pukul 20:00 - 21:00) dibandingkan hari kerja lainnya.
4.  **Rekomendasi Operasional:** Manajemen dapat mengoptimalkan jadwal shift karyawan dengan menambah personel di dapur pada jendela waktu pukul 11:30 - 13:30 dan 17:00 - 19:30 guna memastikan *lead time* pembuatan pizza tetap terjaga meskipun pesanan melonjak.

**Proporsi Kejadian Komplain di DQPizza**

_Bagaimana perbandingan jumlah pesanan yang disertai keluhan (complain) dan yang tidak disertai keluhan berdasarkan data?_

* Gunakan data transaksi dari dataset DQPizza yang mencatat apakah suatu pesanan memiliki keluhan atau tidak.
* Kelompokkan data berdasarkan status keluhan untuk membedakan antara pesanan “Complain” dan “No Complain”.
* Hitung jumlah pesanan pada masing-masing kelompok untuk mengetahui proporsi antara kedua jenis transaksi tersebut.
* Gunakan hasilnya untuk memahami tingkat kepuasan pelanggan secara umum.
* Analisis lebih lanjut dapat dilakukan untuk mencari tahu penyebab utama keluhan atau bagian proses pelayanan yang perlu ditingkatkan.
* Expected Output :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Proporsi%20Kejadian%20Komplain%20di%20DQPizza.png" width="30%">



In [4]:
%%bigquery proportion_complain --project {project_id} --verbose
SELECT
  CASE
    WHEN is_complain = 1 THEN 'Complain'
    ELSE 'No Complain'
  END AS is_complain,
  COUNT(DISTINCT order_id) AS total_complain
FROM
  dqpizza.tbl_detail_transaction
GROUP BY
  is_complain

Executing query with job ID: aeba661c-cde1-49a5-8c60-1f96799ac50e
Query executing: 0.91s
Job ID aeba661c-cde1-49a5-8c60-1f96799ac50e successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [5]:
display(proportion_complain)

,is_complain,total_complain
0,No Complain,19212
1,Complain,2134


In [6]:
#@title ***Proporsi Kejadian Komplain di DQPizza*** {display-mode: 'form'}

# Import library untuk visualisasi
import plotly.express as px

# Hitung total data
total_data = proportion_complain['total_complain'].sum()

# Warna
hijau_pucat = '#E0ECE4'
merah = '#FF4B5C'

# Buat pie chart
fig = px.pie(
    values = proportion_complain['total_complain'],
    names = proportion_complain['is_complain'],
    color_discrete_sequence = [hijau_pucat, merah],
    hole = 0.65
)

# Atur posisi label
fig.update_traces(
    textposition = 'outside',
    textinfo = 'percent+label',
    hovertemplate='<b>%{label}</b><br>%{value} Customers'
)

# Atur luas grafik, hapus legend dan beri judul
fig.update_layout(
    width = 800,
    height = 600,
    showlegend = False,
    margin = dict(l=160, r=200, t=100, b=30),
    title = dict(
        text = f"<b>Proporsi Kejadian Komplain di DQPizza</b><br>",
        font = dict(
            size = 25,
            color = '#757882'
        ),
        y = 0.92,
        x = 0.46
    )
)

# Berikan informasi total pelanggan di tengah donut chart
fig.add_annotation(
    text = f'Total Transaksi<br><b><span style="font-size: 28px;">{total_data}</b></span>',
    x = 0.5,
    y = 0.5,
    showarrow = False,
    font = dict(size = 30)
)

# Tampilkan grafik
fig.show()

**Kesimpulan :**

...

**Detail Komplain yang Terjadi di DQPizza**

_Jenis keluhan apa saja yang paling sering muncul pada pesanan pelanggan berdasarkan data transaksi?_

* Gunakan data transaksi dari dataset DQPizza yang memuat informasi detail keluhan pelanggan.
* Saring data agar hanya mencakup pesanan yang memiliki keluhan.
* Kelompokkan data berdasarkan jenis atau kategori keluhan yang tercatat.
* Hitung jumlah kemunculan setiap jenis keluhan untuk mengetahui keluhan yang paling sering terjadi.
* Urutkan hasilnya dari jumlah terkecil hingga terbesar agar terlihat pola umum dan prioritas perbaikan layanan.
* Gunakan hasil ini untuk mengidentifikasi area yang perlu ditingkatkan, seperti kualitas produk, waktu pengantaran, atau pelayanan pelanggan.
* Expected Output :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Detail%20Komplain%20yang%20Terjadi%20di%20DQPizza.png" width="30%">

In [7]:
%%bigquery total_detail_complain --project {project_id} --verbose
SELECT
  complain_detail,
  COUNT(order_details_id) AS jumlah_complain
FROM
  dqpizza.tbl_detail_transaction
WHERE
  is_complain = 1
GROUP BY
  complain_detail
ORDER BY
  jumlah_complain ASC

Executing query with job ID: 53db6417-32f6-41be-bc84-cace2c1f9c06
Query executing: 0.61s
Job ID 53db6417-32f6-41be-bc84-cace2c1f9c06 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [8]:
# Tampilkan hasilnya
display(total_detail_complain)

,complain_detail,jumlah_complain
0,Rude staff at counter,112
1,Dough undercooked,260
2,Drink was missing,395
3,Wrong pizza size,558
4,Received wrong pizza,639
5,Order took too long,693
6,Pizza was burnt,1030
7,Missing toppings,1186


In [9]:
#@title ***Detail Komplain yang Terjadi di DQPizza*** {display-mode: 'form'}

import plotly.express as px

total_detail_complain['Color'] = total_detail_complain['jumlah_complain'].apply(
    lambda x: 'Top' if x == total_detail_complain['jumlah_complain'].max() else 'Other'
)

fig = px.bar(
    total_detail_complain,
    x = 'jumlah_complain',
    y = 'complain_detail',
    orientation = 'h',
    color = 'Color',
    color_discrete_map = {
        'Other': '#ffb3b3',
        'Top': '#ff0000'
    },
    text_auto = True
)

fig.update_layout(
    width = 950,
    height = 450,
    xaxis_title = '',
    yaxis_title = '',
    showlegend = False,
    plot_bgcolor = 'rgba(0, 0, 0, 0)',
    title = dict(
        text = '<b>Detail Komplain yang Terjadi di DQPizza</b><br><sup><sup>Periode 2024</sup></sup>',
        font = dict(color = '#ff0000')
    )
)

fig.update_xaxes(showticklabels = False)

fig.update_traces(
    textposition = 'inside',
    hovertemplate = '<b>Pizza %{label}</b><br>Total Order = %{value}'
)

fig.show()


### **Kesimpulan :**

Berdasarkan analisis visualisasi **Detail Komplain yang Terjadi di DQPizza**, dapat disimpulkan beberapa poin utama untuk perbaikan layanan:

1.  **Prioritas Utama (Kualitas Produk):** Keluhan terbanyak adalah **'Missing toppings'** (1.186) dan **'Pizza was burnt'** (1.030). Ini menunjukkan bahwa masalah utama terletak pada proses *food preparation* dan *cooking*. Diperlukan pelatihan ulang bagi staf dapur mengenai standar resep dan pengawasan suhu oven.
2.  **Akurasi Pesanan:** Masalah **'Received wrong pizza'** (639) dan **'Wrong pizza size'** (558) menunjukkan adanya miskomunikasi dalam pencatatan atau pengambilan pesanan. Implementasi sistem cek ganda (double-check) sebelum pengantaran sangat disarankan.
3.  **Efisiensi Waktu:** Sebanyak 693 komplain terkait **'Order took too long'**. Hal ini selaras dengan analisis jam sibuk sebelumnya, di mana manajemen perlu menambah personel pada jam makan siang dan makan malam untuk mempercepat waktu pelayanan.
4.  **Aspek Positif:** Keluhan terhadap **'Rude staff at counter'** adalah yang paling sedikit (112), yang menandakan bahwa keramahan staf garis depan sudah cukup baik, namun tetap perlu dipertahankan.

**Jumlah Detail Komplain per Pizza Order Maker**

_Bagaimana frekuensi dan jenis keluhan pelanggan yang diterima oleh masing-masing pembuat pizza (order maker) berdasarkan data transaksi?_

* Gunakan data transaksi dari dataset DQPizza yang memuat informasi tentang pembuat pizza (order maker) dan detail keluhan pelanggan.
* Identifikasi setiap keluhan yang tercatat untuk setiap pembuat pizza.
* Hitung jumlah kemunculan setiap jenis keluhan pada masing-masing pembuat pizza untuk mengetahui pola atau tren tertentu.
* Ubah tampilan data agar setiap jenis keluhan menjadi kolom, sehingga mudah dibandingkan antar pembuat pizza.
* Urutkan hasilnya berdasarkan pembuat pizza untuk melihat siapa yang paling sering menerima keluhan dan jenis keluhannya.
* Gunakan hasil analisis ini untuk menilai kinerja masing-masing pembuat pizza, serta menentukan area pelatihan atau peningkatan kualitas produksi yang dibutuhkan.
* *Expected Output* :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Jumlah%20Detail%20Komplain%20per%20Pizza%20Order%20Maker.png" width="100%">

In [12]:
%%bigquery total_complain_per_ordermaker --project {project_id} --verbose
SELECT
  *
FROM (
  SELECT
    order_maker_id,
    complain_detail
  FROM
    dqpizza.tbl_detail_transaction
  WHERE
    is_complain = 1
) PIVOT (
  COUNT(complain_detail) FOR complain_detail IN (
    'Missing toppings',
    'Pizza was burnt',
    'Order took too long',
    'Received wrong pizza',
    'Wrong pizza size',
    'Drink was missing',
    'Dough undercooked',
    'Rude staff at counter'
  )
)
ORDER BY
  order_maker_id ASC

Executing query with job ID: 6edc3ab6-5f6e-462d-b129-c912ad5108ac
Query executing: 1.65s
Job ID 6edc3ab6-5f6e-462d-b129-c912ad5108ac successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [14]:
# Tampilkan hasilnya
display(total_complain_per_ordermaker)

,order_maker_id,Missing toppings,Pizza was burnt,Order took too long,Received wrong pizza,Wrong pizza size,Drink was missing,Dough undercooked,Rude staff at counter
0,EMP000208,96,118,61,68,43,42,32,11
1,EMP000231,112,94,83,83,40,32,21,7
2,EMP000286,106,112,87,78,71,40,24,3
3,EMP000295,136,94,55,39,49,40,26,32
4,EMP000302,122,82,51,60,65,33,34,10
5,EMP000437,155,91,72,39,56,57,39,7
6,EMP000560,98,112,69,77,54,72,24,11
7,EMP000646,114,109,80,47,67,26,33,4
8,EMP000665,98,78,87,84,74,21,18,11
9,EMP000756,149,140,48,64,39,32,9,16


In [15]:
#@title ***Jumlah Detail Komplain per Pizza Order Maker*** {display-mode: 'form'}

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = px.imshow(
    total_complain_per_ordermaker.set_index('order_maker_id'),
    text_auto = True,
)

fig.update(
    layout_coloraxis_showscale = False
)

fig.update_layout(
    height = 1000,
    width = 800,
    coloraxis_colorscale = 'reds',
    xaxis_tickangle = 0,
    plot_bgcolor = 'rgba(0, 0, 0, 0)',
    paper_bgcolor = 'rgba(0, 0, 0, 0)',
    title = dict(
        text = '<b>Jumlah Detail Komplain per <i>Pizza Order Maker</i></b><br><sup><sup>Periode 2024</sup></sup>',
        font = dict(
            color = '#B54B1F',
            size = 20
        )
    ),
    margin=dict(t=150)
)

fig.update_xaxes(
    tickangle = -15,
    side = 'top',
    automargin = True,
    title = None,
    tickfont = dict(size=11)
)

fig.update_yaxes(
    title = None,
    tickfont = dict(size=11)
)

fig.show()

### **Kesimpulan :**

Berdasarkan analisis visualisasi **Jumlah Detail Komplain per Pizza Order Maker**, kita dapat menarik beberapa poin evaluasi kinerja:

1.  **Identifikasi Karyawan dengan Keluhan Tertinggi:** Beberapa pembuat pizza menunjukkan angka keluhan yang lebih menonjol dibandingkan yang lain. Contohnya, **EMP000295** memiliki jumlah keluhan tertinggi pada kategori *'Missing toppings'* (136 keluhan) dan **EMP000208** pada kategori *'Pizza was burnt'* (118 keluhan).
2.  **Spesialisasi Masalah:** Setiap *order maker* cenderung memiliki pola kesalahan yang spesifik. Ada staf yang lebih sering mengalami masalah pada akurasi *topping*, sementara yang lain pada kontrol waktu pembakaran (gosong).
3.  **Rekomendasi Pelatihan (Targeted Training):** Daripada melakukan pelatihan umum, manajemen dapat memberikan *coaching* yang lebih spesifik. Staf dengan angka *'Pizza was burnt'* tinggi perlu dilatih kembali dalam penggunaan oven, sedangkan staf dengan angka *'Missing toppings'* tinggi perlu ditekankan pada ketelitian membaca detail pesanan.
4.  **Standarisasi Produksi:** Perbedaan angka yang kontras antar staf menunjukkan perlunya standarisasi prosedur operasional di dapur agar kualitas pizza yang dihasilkan tetap konsisten siapapun yang membuatnya.

## **Area 4 - Customer**

**Distribusi Usia Pelanggan**

_Bagaimana distribusi usia pelanggan berdasarkan kategori gender?_

* Gunakan data pelanggan dari dataset DQPizza yang memuat informasi usia dan jenis kelamin pelanggan.
* Kelompokkan data berdasarkan kategori gender, seperti laki-laki dan perempuan.
* Amati sebaran usia di masing-masing kelompok untuk melihat apakah terdapat perbedaan karakteristik pelanggan berdasarkan gender.
* Analisis pola umum, misalnya kelompok usia mana yang paling dominan dalam tiap gender.
* Gunakan hasil analisis ini untuk mendukung strategi pemasaran yang lebih tepat sasaran, seperti segmentasi promosi atau penawaran menu khusus bagi kelompok pelanggan tertentu
* *Expected Output* :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Distribusi%20Usia%20Pelanggan.png" width="30%">

In [6]:
%%bigquery age_and_gender --project {project_id} --verbose
SELECT
  customer_gender,
  customer_age
FROM
  dqpizza.tbl_detail_transaction

Executing query with job ID: 6028ee59-69eb-4bd5-88f8-9075fc8af590
Query executing: 1.40s
Job ID 6028ee59-69eb-4bd5-88f8-9075fc8af590 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [7]:
# Tampilkan hasilnya
display(age_and_gender)

,customer_gender,customer_age
0,M,51
1,M,51
2,M,51
3,M,51
4,M,51
...,...,...
48614,F,31
48615,F,31
48616,F,31
48617,F,31


In [8]:
# @title ***Distribusi Usia Pelanggan*** {display-mode: 'form'}

# Import library yang dibutuhkan
import plotly.figure_factory as ff

def distribution_plot(data_cat_1, data_cat_2, label, column_name):
    # Group data together
    data_cat_1 = data_cat_1[column_name]
    data_cat_2 = data_cat_2[column_name]
    hist_data = [data_cat_1, data_cat_2]
    group_labels = label

    # Create distplot with custom bin_size
    fig = ff.create_distplot(
        hist_data,
        group_labels,
        show_hist = False,
        show_rug = False
    )

    fig.update_layout(
        plot_bgcolor = 'rgba(0, 0, 0, 0)',
        title = dict(
            text = f"<b>Distribusi Usia Pelanggan</b>",
            font = dict(
                size = 28,
                color = 'black'
            ),
            y = 0.92,
            x = 0.5
        )
    )

    fig.update_xaxes(showline=True, linewidth=1, linecolor='black')
    fig.update_yaxes(showline=True, linewidth=1, linecolor='black')

    # Tampilkan visualisasi
    fig.show()

male_cust = age_and_gender[age_and_gender['customer_gender'] == 'M']
female_cust = age_and_gender[age_and_gender['customer_gender'] == 'F']
label_grup =  ['Male', 'Female']

distribution_plot(male_cust, female_cust, label_grup, 'customer_age')

### **Kesimpulan :**

Berdasarkan visualisasi **Distribusi Usia Pelanggan**, berikut adalah beberapa temuan utama:

1.  **Profil Demografis Dominan:** Pelanggan DQPizza didominasi oleh kelompok usia produktif, yaitu antara **25 hingga 40 tahun**. Karakteristik distribusi ini terlihat konsisten baik pada pelanggan laki-laki maupun perempuan.
2.  **Kemiripan Karakteristik Gender:** Tidak terdapat perbedaan signifikan dalam distribusi usia antara pria dan wanita. Keduanya memiliki pola kurva yang serupa, yang menunjukkan bahwa preferensi terhadap produk pizza tidak dipengaruhi oleh perbedaan usia antar gender secara kontras.
3.  **Implikasi Strategi Pemasaran:** Mengingat mayoritas pelanggan adalah dewasa muda, konten pemasaran sebaiknya difokuskan pada platform digital dengan gaya visual yang modern. Promosi seperti *'After Office Hour'* atau *'Combo Makan Siang'* akan sangat efektif bagi kelompok usia ini.
4.  **Peluang Pertumbuhan:** Rendahnya proporsi pelanggan di bawah 20 tahun dan di atas 50 tahun membuka peluang untuk kampanye baru, seperti paket khusus pelajar atau menu keluarga untuk menarik demografi yang lebih luas.

**Preferensi Kategori Pizza per Order**

_Bagaimana preferensi kategori pizza berdasarkan gender pelanggan pada data transaksi?_

* Gunakan data transaksi dari dataset DQPizza yang mencakup informasi tentang jenis kelamin pelanggan dan kategori pizza yang dipesan.
* Kelompokkan data berdasarkan kombinasi antara gender pelanggan dan kategori pizza.
* Hitung jumlah pesanan di setiap kategori untuk masing-masing gender agar terlihat kategori pizza mana yang paling disukai oleh setiap kelompok pelanggan.
* Urutkan hasilnya berdasarkan gender dan jumlah pesanan terbanyak untuk memperjelas perbandingan antar kelompok.
* Gunakan hasil analisis ini untuk merancang strategi pemasaran yang lebih terarah, seperti promosi menu tertentu untuk segmen pelanggan laki-laki atau perempuan.
* *Expected Output* :<br><br><img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/DQProject%20-%20Expected%20Output%20Preferensi%20Kategori%20Pizza%20per%20Order.png" width="40%">

In [9]:
%%bigquery pizza_order_per_gender --project {project_id} --verbose

SELECT
  customer_gender,
  pizza_category,
  COUNT(order_id) AS total_pizza_category
FROM
  dqpizza.tbl_detail_transaction
GROUP BY
  customer_gender,
  pizza_category
ORDER BY
  customer_gender ASC,
  total_pizza_category DESC

Executing query with job ID: 133dc1ec-d368-450d-b850-38588904e163
Query executing: 0.52s
Job ID 133dc1ec-d368-450d-b850-38588904e163 successfully executed


Query is running:   0%|          |

Downloading:   0%|          |

In [10]:
# Tampilkan hasilnya
display(pizza_order_per_gender)

,customer_gender,pizza_category,total_pizza_category
0,F,CLASSIC,6934
1,F,SUPREME,5568
2,F,VEGGIE,5431
3,F,CHICKEN,5213
4,M,CLASSIC,7647
5,M,SUPREME,6209
6,M,VEGGIE,6016
7,M,CHICKEN,5601


In [11]:
#@title ***Preferensi Kategori Pizza per Order*** {display-mode: 'form'}

import pandas as pd
import numpy as np
import plotly.express as px

pivot = pizza_order_per_gender.pivot_table(
    index='pizza_category',
    columns='customer_gender',
    values='total_pizza_category',
    aggfunc='sum',
    fill_value=0
).reset_index()

gender_cols = [c for c in pivot.columns if c != 'pizza_category']
if len(gender_cols) < 2:
    raise ValueError("Butuh minimal dua kategori gender untuk butterfly chart.")
g1, g2 = gender_cols[0], gender_cols[1]

pivot[f'{g1}_neg'] = -pivot[g1]

fig = px.bar(
    pivot,
    y='pizza_category',
    x=[f'{g1}_neg', g2],
    orientation='h',
    text_auto=True,
    title=f'<b>Preferensi Kategori Pizza per Gender: {g1} vs {g2}</b>',
    labels={'pizza_category': 'Pizza Category'}
)

max_val = int(max(pivot[g1].max(), pivot[g2].max()))
xticks = np.linspace(-max_val, max_val, 9)
xticktext = [str(abs(int(x))) for x in xticks]

fig.update_layout(
    yaxis_title=None,
    barmode='relative',
    bargap=0.2,
    height=700,
    width=1000,
    plot_bgcolor='rgba(0,0,0,0)',
    paper_bgcolor='rgba(0,0,0,0)',
    xaxis=dict(
        tickmode='array',
        tickvals=xticks,
        ticktext=xticktext,
        title='Jumlah Pesanan'
    ),
    legend_title_text='Gender'
)

fig.update_xaxes(showticklabels=False)
fig.update_traces(texttemplate='%{text}', textposition='inside')

# --- Ubah nama trace agar legend tampil rapi (tanpa _neg) ---
fig.data[0].name = g1
fig.data[1].name = g2

# --- Pastikan nilai teks selalu positif ---
for trace in fig.data:
    vals = np.abs(trace.x)
    trace.text = vals
    trace.textfont = dict(color='white', size=11)

fig.add_vline(x=0, line_width=1, line_color='black')

fig.show()


### **Kesimpulan :**

Berdasarkan visualisasi **Preferensi Kategori Pizza per Gender**, kita dapat menyimpulkan beberapa poin penting:

1.  **Kategori Favorit Universal:** Kategori **CLASSIC** merupakan pilihan utama bagi kedua kelompok gender, dengan total pesanan mencapai 7.647 oleh laki-laki dan 6.934 oleh perempuan.
2.  **Volume Pesanan:** Secara keseluruhan, pelanggan laki-laki (M) memiliki volume transaksi yang lebih besar di setiap kategori pizza dibandingkan pelanggan perempuan (F).
3.  **Urutan Preferensi yang Identik:** Menariknya, kedua gender memiliki urutan selera yang sama, yaitu: **Classic > Supreme > Veggie > Chicken**. Hal ini menunjukkan bahwa tren selera pasar di DQPizza cukup homogen dan tidak terlalu dipengaruhi oleh perbedaan gender.
4.  **Rekomendasi Strategi:** Karena kategori 'Chicken' memiliki jumlah pesanan terendah di kedua gender, manajemen bisa mempertimbangkan promosi khusus atau inovasi resep pada kategori ini untuk meningkatkan daya tariknya. Sementara itu, kategori 'Classic' dapat terus dijadikan menu andalan dalam setiap kampanye iklan utama.

Kamu memiliki
<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Aksara%20Welcome.png" width="25%">

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---

<br>
<a href="https://www.linkedin.com/in/bachtiyarma/"><img src="https://img.shields.io/badge/-© 2025 Bachtiyar M. Arief-417DAC?style=for-the-badge&logoColor=white"/></a>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>
